"""fix employee table order with batch FK creation

Revision ID: 40e92ce529bf
Revises: 
Create Date: 2026-08-18 10:07:48.174618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e92ce529bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables without foreign key constraints first
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('position_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    op.create_table('evaluation_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.CheckConstraint('"order" > 0', name='ck_question_order_positive'),
    sa.CheckConstraint('weight > 0', name='ck_question_weight_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('evaluation_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False),
    sa.Column('evaluation_year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluator_id', 'employee_id', 'evaluation_year', 'week_number', name='uq_evaluator_employee_week')
    )
    
    op.create_table('leader_lead',
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('leader_id <> lead_id', name='chk_no_self_lead'),
    sa.PrimaryKeyConstraint('leader_id', 'lead_id')
    )
    
    op.create_table('evaluation_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_summary_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 4', name='ck_response_score_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_summary_id', 'question_id', name='uq_eval_response_summary_question')
    )
    
    # Now add foreign key constraints in batch operations
    with op.batch_alter_table('evaluation_summary', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_eval_summary_employee_id', 'employee', ['employee_id'], ['id'])
        batch_op.create_foreign_key('fk_eval_summary_evaluator_id', 'employee', ['evaluator_id'], ['id'])
        batch_op.create_index('ix_eval_summary_latest', ['employee_id', 'evaluator_id', 'evaluation_date'], unique=False)

    with op.batch_alter_table('leader_lead', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_leader_lead_leader_id', 'employee', ['leader_id'], ['id'])
        batch_op.create_foreign_key('fk_leader_lead_lead_id', 'employee', ['lead_id'], ['id'])
        batch_op.create_index('ix_leader_lead_reverse', ['lead_id'], unique=False)

    with op.batch_alter_table('evaluation_response', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_eval_response_summary_id', 'evaluation_summary', ['evaluation_summary_id'], ['id'])
        batch_op.create_foreign_key('fk_eval_response_question_id', 'evaluation_question', ['question_id'], ['id'])
        batch_op.create_index('ix_eval_response_question', ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_response', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_response_question')
        batch_op.drop_constraint('fk_eval_response_question_id', 'foreignkey')
        batch_op.drop_constraint('fk_eval_response_summary_id', 'foreignkey')

    with op.batch_alter_table('leader_lead', schema=None) as batch_op:
        batch_op.drop_index('ix_leader_lead_reverse')
        batch_op.drop_constraint('fk_leader_lead_lead_id', 'foreignkey')
        batch_op.drop_constraint('fk_leader_lead_leader_id', 'foreignkey')

    with op.batch_alter_table('evaluation_summary', schema=None) as batch_op:
        batch_op.drop_index('ix_eval_summary_latest')
        batch_op.drop_constraint('fk_eval_summary_evaluator_id', 'foreignkey')
        batch_op.drop_constraint('fk_eval_summary_employee_id', 'foreignkey')

    op.drop_table('evaluation_response')
    op.drop_table('leader_lead')
    op.drop_table('evaluation_summary')
    op.drop_table('evaluation_question')
    op.drop_table('employee')
    # ### end Alembic commands ###